### ISSUE TITLE
Данные для обучения на русском языке

### ISSUE THREAD

**Issue by Usharovsky** [w2vxx/w2vxx#1]
Добрый день!
Возможно ли использование русского языка в обучении?

**Comment by parus-proj** [comment]
День добрый!
Да, возможно. Построение русскоязычных векторных представлений тестировал под Linux (тренировочное множество в utf-8). Это работает. 
Под Windows обучение должно сработать при условии однобайтного кодирования пробельных символов (cp866, windows-1251, utf-8). Работа утилиты distance будет зависеть от того, в какой кодировке у вас обучающее множество и консоль. В программе отсутствует перекодировочная логика. С русским языком под Windows не тестировал. В Windows 10 я бы рекомендовал работать с обучающим множеством в utf-8 и переключить консоль (командой chcp) в эту же кодировку (пишут, что в Windows 10 есть такая возможность). Это наиболее близко к тестировавшейся Linux-конфигурации.
Русскоязычный корпус для обучения (разумного объема) могу подготовить и опубликовать.

**Comment by Usharovsky** [comment]
Спасибо! 
Разработка под Linux.
Корпус у нас свой.
